Repository VOLTTRON/copier-poetry-volttron-agent, pull requests merged in 2022-04, with the labels that each got.

#18 2nd attempt
  Makefile
  mkdocs.yml
  project/Makefile.jinja
  project/[[ python_package_distribution_name ]]/[[ python_package_import_name ]]/__main__.py.jinja
  project/[[ python_package_distribution_name ]]/[[ python_package_import_name ]]/cli.py.jinja
  project/[[ python_package_distribution_name ]]/__init__.py.jinja
  project/[[ python_package_distribution_name ]]/agent.py.jinja
  project/config/coverage.ini.jinja
  project/config/flake8.ini
  project/config/mypy.ini
  project/config/pytest.ini
  project/duties.py.jinja
  project/mkdocs.yml.jinja
  project/scripts/multirun.sh
  project/scripts/setup.sh
  project/tests/conftest.py
  project/tests/conftest.py.jinja
  tests/test_generate.sh
  tests/test_licenses.sh
Labels: agent-tooling

#25 Move code_analysis workflow to project dir
  project/.github/workflows/code_analysis.yml
Labels: bug

#26 Change branch to main in ci.yml workflow
  .github/workflows/ci.yml
Labels: bug

#27 Add mypy.ini to project dir
  project/mypy.ini
Labels: agent-tooling

#28 Add create release and publish to pypi workflows
  project/.github/workflows/create_release.yml
  project/.github/workflows/publish_to_pypi.yml
Labels: agent-tooling

#23 12 update the docs section to use sphinx
  project/docs/Makefile.jinja
  project/docs/changelog.md
  project/docs/code_of_conduct.md
  project/docs/contributing.md
  project/docs/credits.md
  project/docs/css/mkdocstrings.css
  project/docs/index.md
  project/docs/license.md
  project/docs/macros.py
  project/docs/reference/cli.md.jinja
  project/docs/requirements.txt.jinja
  project/docs/source/conf.py.jinja
  project/docs/source/index.rst.jinja
Labels: agent-tooling

#17 Add copier sequence diagram
  README.md
  copier_workflow.png
  copier_workflow.txt
Labels: documentation

#31 change question prompt default answers
  copier.yml
Labels: agent-tooling

#40 Update README
  project/README.md.jinja
Labels: documentation

#43 Add example config file
  project/config
Labels: documentation, agent-tooling

#45 Update agent.py template
  project/src/[[ python_package_import_name ]]/agent.py.jinja
Labels: agent-tooling

#30 updated to follow https://github.com/VOLTTRON/volttron-core/blob/v10.…
  project/.pre-commit-config.yaml
Labels: agent-tooling

#41 8 make readme more clear and user friendly
  README.md
Labels: documentation

#42 Update pyproject.toml; update docs folder
  project/README.md.jinja
  project/docs/requirements.txt.jinja
  project/pyproject.toml.jinja
Labels: documentation, agent-tooling

#48 Fix pyproject.toml packages section
  project/pyproject.toml.jinja
Labels: bug
